In [1]:
import numpy as np

In [56]:
arr=np.array([[2,3,4],[5,9,10],[6,7,4],[8,1,3]])
arr.shape
x=arr.copy()
y=arr.copy()

In [47]:
for i in arr:
    i+=10
arr

array([[12, 13, 14],
       [15, 19, 20],
       [16, 17, 14],
       [18, 11, 13]])

In [48]:
for i in x:
    i*=2
x

array([[ 4,  6,  8],
       [10, 18, 20],
       [12, 14,  8],
       [16,  2,  6]])

In [57]:
y.flatten().shape

(12,)

In [70]:
arr.reshape(2,-1)

array([[ 2,  3,  4,  5,  9, 10],
       [ 6,  7,  4,  8,  1,  3]])