In [2]:
    print("ML 101")

ML 101


In [4]:
import tensorflow as tf
from tensorflow import keras

ModuleNotFoundError: No module named 'tensorflow'

In [6]:
import numpy as np


In [7]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
[1,2,3,4,5]

[1, 2, 3, 4, 5]

In [9]:
type([1,2,3,4,5])

list

In [10]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [12]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
x=[[1,2]]
np_x=np.array(x)
np_x

array([[1, 2]])

array([1, 2, 3, 4, 5, 7, 8])

In [43]:
np_x.mean()

1.5

In [44]:
np_x.astype('str')

array([['1', '2']], dtype='<U11')

In [45]:
np_x.ndim

2

In [47]:
for i in np_x:
        print(i)


[1 2]


In [48]:
for i in np_x:
    for j in i:
        print(j)


1
2


In [78]:
x=[[1,2,0],[3,4,0],[5,6,0],[7,8,0]]
np_x=np.array(x)
np_x

array([[1, 2, 0],
       [3, 4, 0],
       [5, 6, 0],
       [7, 8, 0]])

In [80]:
np_x.ndim

2

In [125]:
np_x[::-3,0]

array([7, 1])

In [126]:
arr=np.array(['apple','banana','cherry'])

In [127]:
arr.dtype

dtype('<U6')